/**:
  ros__parameters:
    # # Definitions of tags to detect
    #
    # ## General remarks
    #
    # - All length in meters
    # - Ellipsis (...) signifies that the previous element can be repeated multiple times.
    #
    # ## Standalone tag definitions
    # ### Remarks
    #
    #
    # ### Syntax
    #
    # standalone_tags:
    #   tag_names: ["TAG_NAME", ...]
    #   TAG_NAME:
    #     id: ID
    #     size: SIZE
    #   ...
    #
    standalone_tags:
      tag_names: [tag_99]
      tag_99:
        id: 99
        size: 0.033

    # # ## Tag bundle definitions
    # # ### Remarks
    # #
    # # - x, y, z have default values of 0 thus they are optional
    # # - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
    # #
    # # ### Syntax
    # #
    # # tag_bundles:
    # #   bundle_names: ["CUSTOM_BUNDLE_NAME", ...]
    # #   CUSTOM_BUNDLE_NAME:
    # #     layout:
    # #       ids: [ID, ...]
    # #       ID:
    # #         size: SIZE
    # #         x: X_POS
    # #         y: Y_POS
    # #         z: Z_POS
    # #         qw: QUAT_W_VAL
    # #         qx: QUAT_X_VAL
    # #         qy: QUAT_Y_VAL
    # #         qz: QUAT_Z_VAL
    # #       ...
    # #   ...
    # tag_bundles:
    #   bundle_names: ["bundle_0"]
    #   bundle_0:
    #     layout:
    #       ids: [1]
    #       1:
    #         size: 0.033
    tag_bundles:
      bundle_names: ["table_0", "table_1"]
      table_1:
        layout:
          ids: [8, 9, 10, 11, 12, 13, 14, 15]
          8:
            size: 0.075
            x: -0.455
            y: 0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          9:
            size: 0.075
            x: 0.0
            y: 0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          10:
            size: 0.075
            x: 0.455
            y: 0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          11:
            size: 0.075
            x: -0.455
            y: -0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          12:
            size: 0.075
            x: 0.0
            y: -0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          13:
            size: 0.075
            x: 0.455
            y: -0.255
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0
          14:
            size: 0.075
            x: -0.25
            y: -0.15
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0
          15:
            size: 0.075
            x: 0.25
            y: -0.15
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

      table_0:
        layout:
          ids: [0, 1, 2, 3, 4, 5, 6, 7]
          0:
            size: 0.075
            x: -0.355
            y: 0.355
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          1:
            size: 0.075
            x: 0.355
            y: 0.355
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          2:
            size: 0.075
            x: -0.355
            y: -0.355
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          3:
            size: 0.075
            x: 0.355
            y: -0.355
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0
          4:
            size: 0.075
            x: -0.2
            y: 0.2
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          5:
            size: 0.075
            x: 0.2
            y: 0.2
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          6:
            size: 0.075
            x: -0.2
            y: -0.2
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0

          7:
            size: 0.075
            x: 0.2
            y: -0.2
            z: 0.0
            qw: 0.0
            qx: 0.0
            qy: 0.0
            qz: 0.0
